# Site Info
#==================================
# url: https://seokhoonj.github.io
# baseurl: 
# page path:
title: 'LeArN mOrE'
tagline: 'stay with problems longer'
description: 'stay with problems longer'
baseurl: ''
url: 'http://seokhoonj.github.io'
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: seokhoonj
  description: <strong>We are all sensitive people with so much to give.</strong>
  # gravatar: # 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/seokhoonj
    github:    https://github.com/seokhoonj
    # facebook:  <hide>
    # twitter:   https://twitter.com/
    # weibo:     http://weibo.com/41173780
    email:     mailto:seokhoonj@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/blog/categories/'
  categories:           
    - '/blog/categories/'
    - { R: '/blog/categories/#R' }
    - { Python: '/blog/categories/#Python' }
    - { Vim: '/blog/categories/#Vim' }
    - { Math: '/blog/categories/#Math' }
    - { Django: '/blog/categories/#Django' }
    - { Etc: '/blog/categories/#Etc' }
    - { Presentation: '/blog/categories/#Presentation' }
#  Presentation:
#    - '/presentation/systemtrading/'
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/seokhoonj/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: # /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: # Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-127719266-1' # leave blank if you don't want google analytics
disqus_short_name: 'seokhoonj-github-io' # leave blank if you don't want disqus
